title: Brush Stroke Parameterized Style Transfer
author: Uma Maheswara R Meleti
email: maheshmeleti350@gmail.com
theme: minima
plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled: true
  strip_title: true
  collections: true

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/maheshmeleti/brushstroke-parameterized-style-transfer-pytorch" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/mahesh-meleti/" }